### ISSUE TITLE
Support for Misago 0.10

### ISSUE THREAD

**Issue by ghost** [rafalp/misago-ga#1]
Does this work with the new Misago codebase?

**Comment by rafalp** [comment]
No, starting with Misago 0.6 you are supposed to override templates instead.

**Comment by ghost** [comment]
Ah, okay. Thanks for clearing this up!

**Comment by rafalp** [comment]
Misago has `jumbotron.html` template thats blank and gets included right after `<body>`, making your GA code execute as soon as user hits your page. That's what I'm using.
